### ISSUE TITLE
Narrowing conversion warning in shoc_functions_f90

### ISSUE THREAD

**Issue by bartgol** [E3SM-Project/scream#524]
My compiler reports the following warning.

```
shoc_functions_f90.cpp:429:82: warning: narrowing conversion of ‘nlevi’ from ‘ekat::Int’ {aka ‘int’} to ‘long unsigned int’ inside { } [-Wnarrowing]
```

Apparently, this is not good. See [standard 8.5.4 item 3](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf):

```
  If a narrowing conversion (see below) is required to convert any of the arguments, the program is ill-formed.
```

**Comment by jeff-cohere** [comment]
I saw this earlier today and fixed it while trying to reproduce a build error, as it happens! Stand by.

**Comment by PeterCaldwell** [comment]
I think this is fixed but don't want to close the issue myself in case I'm wrong. @bartgol @jeff-cohere - would one of you mind confirming/closing?

**Comment by bartgol** [comment]
I think I still get a ton of those:

```
shoc_functions_f90.cpp:1083:52: warning: narrowing conversion of ‘nlevi’ from ‘ekat::Int’ {aka ‘int’} to ‘long unsigned int’ inside { } [-Wnarrowing]
```
@jgfouca Perhaps we need to wait till after the next ekat upgrade?

**Comment by jgfouca** [comment]
@bartgol , yes, #819 will fix this.

**Comment by PeterCaldwell** [comment]
Since #819 is integrated, I think we can close this issue? @jgfouca , would you do the honors?
